### ISSUE TITLE
gastos duplicados no relatório

### ISSUE THREAD

**Issue by AndreCarvalho94** [okfn-brasil/serenata-relatorio-catarse#1]
Ao fazer uma consulta no relatório notei que em um dos resultados os gastos apresentavam-se duplicados, foram gerados 4 links, dois repetidos. 
Político: Pedro Fernandes
Partido: PTB/MA
links duplicados: 
https://jarbas.serenata.ai/layers/#/documentId/5465894
https://jarbas.serenata.ai/layers/#/documentId/5550734

**Comment by cuducos** [comment]
Muito obrigado, @AndreCarvalho94 – arrumado : )
